services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: swiftnote_db
      POSTGRES_USER: swift_user
      POSTGRES_PASSWORD: SwiftKey13
    ports:
      - "5432:5432"
    volumes:
      - swiftnote_postgres:/var/lib/postgresql

volumes:
  swiftnote_postgres:
